### ISSUE TITLE
Embedding this extension into `elia/vscode-textmate`

### ISSUE THREAD

**Issue by elia** [erikphansen/vscode-toggle-column-selection#6]
_First of all, thanks, this extension has been a life-saver while switching from TM2 to VSC 🙌_ 

In order to ease my transition (after 15yrs) I'm building a comprehensive TM2 extension for VS Code and wanted to embed this extension into it, but I couldn't find any LICENSE information anywhere. 

Can I have your permission to do so?

It's all in https://github.com/elia/vscode-textmate
(Happy to add you to the repo as well if you would like)

**Comment by erikphansen** [comment]
Somehow I’m only seeing this now (time to look at my github notification settings 🙄). But, yes, do whatever you want with this code! If you want to add a link back to this repo from your repo, that’d be cool. But I really don’t care that much 😂
